spring.datasource.url=jdbc:postgresql://localhost:5432/emt_lab
spring.flyway.schemas=public
spring.datasource.username=acoslav
spring.datasource.password=acoslav

spring.jpa.hibernate.ddl-auto=validate

logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE
